version: '2'

services:
  rdns-server:
    image: rancher/rdns-server:v0.5.1-rancher-amd64
    network_mode: host
    restart: always
    volumes:
      - ./config:/etc/rdns/config
    environment:
      - ETCD_ENDPOINTS=${ETCD_ENDPOINTS}
      - DOMAIN=${DOMAIN}
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 25m
    command:
      - rdns-server
      - etcdv3