#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

CONST="-X main.DNSVersion=${VERSION} -X main.DNSDate='${BUILD_DATE}'"

mkdir -p bin
GOARCH=$ARCH GOOS=linux CGO_ENABLED=0 go build -ldflags "$CONST -extldflags -static -s -w" -o bin/rdns-server
