#!/bin/bash
set -e

cd $(dirname $0)/..

PACKAGES=". $(find -name '*.go' | xargs -I{} dirname {} |  cut -f2 -d/ | sort -u | grep -Ev '(^\.$|.git|.trash-cache|vendor|bin)' | sed -e 's!^!./!' -e 's!$!/...!')"

go vet ${PACKAGES}

for i in ${PACKAGES}; do
    if [[ -n "$(golint ${i} | grep -v 'should have comment.*or be unexported' | tee /dev/stderr)" ]]; then
        failed=true
    fi
done
test -z "$failed"

test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"
